//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCPervomay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymMembershipServices
    {
        public int Id { get; set; }
        public int GymMembershipId { get; set; }
        public int ServicesId { get; set; }
    
        public virtual GymMembership GymMembership { get; set; }
        public virtual Services Services { get; set; }
    }
}
