//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCPervomay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KidParent
    {
        public int Id { get; set; }
        public int IdKid { get; set; }
        public int IdParent { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
