//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCPervomay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locker
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int LockerRoomId { get; set; }
        public int UserId { get; set; }
    
        public virtual LockerRoom LockerRoom { get; set; }
        public virtual User User { get; set; }
    }
}
