//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCPervomay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDCPervomayEntities : DbContext
    {
        public SDCPervomayEntities()
            : base("name=SDCPervomayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DayOfWeek> DayOfWeek { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<GymMembership> GymMembership { get; set; }
        public virtual DbSet<Locker> Locker { get; set; }
        public virtual DbSet<LockerRoom> LockerRoom { get; set; }
        public virtual DbSet<PersonalTraining> PersonalTraining { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<SectionDayOfWeek> SectionDayOfWeek { get; set; }
    }
}
