//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCPervomay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionDayOfWeek
    {
        public int SectionId { get; set; }
        public int DayOfWeekId { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual DayOfWeek DayOfWeek { get; set; }
        public virtual Section Section { get; set; }
    }
}
