//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDCPervomay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionKid
    {
        public int Id { get; set; }
        public int SectionId { get; set; }
        public int KidId { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual User User { get; set; }
    }
}
